@AuthorizationToken = Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1cm46ZXhhbXBsZTpjbGFpbSI6dHJ1ZSwiaWF0IjoxNjcyMjk5NzAxLCJpc3MiOiJ1cm46ZXhhbXBsZTppc3N1ZXIiLCJhdWQiOiJ1cm46ZXhhbXBsZTphdWRpZW5jZSIsImV4cCI6MTY3MjMxNzcwMX0.i81cFqUAa8aGB2ChTQcjqvDONVS1KUktjVNtmVR0uuU

### Login
POST http://localhost:5001/login HTTP/1.1
Content-Type: application/json

{
    "username": "darren",
    "password": "123456"
}

### Packages list
GET http://localhost:5001/packages HTTP/1.1
Authorization: {{AuthorizationToken}}


### Package Group by Display name
GET http://localhost:5001/packages/groupbydisplayname HTTP/1.1
Authorization: {{AuthorizationToken}}


### Package Distinct Display name
GET http://localhost:5001/packages/distinctdisplayname HTTP/1.1
Authorization: {{AuthorizationToken}}

### Upload Root with correcg JWT
GET http://localhost:5001/upload HTTP/1.1
Authorization: {{AuthorizationToken}}

### Invalid JWT Key
GET http://localhost:5001/packages HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2NzIyMTk5OTcsImV4cCI6MTcwMzc1NTk5NywiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsIkdpdmVuTmFtZSI6IkpvaG5ueSIsIlN1cm5hbWUiOiJSb2NrZXQiLCJFbWFpbCI6Impyb2NrZXRAZXhhbXBsZS5jb20iLCJSb2xlIjpbIk1hbmFnZXIiLCJQcm9qZWN0IEFkbWluaXN0cmF0b3IiXX0.27ufjFlWo_EQ-OXnptaWGIuHvgZSZKrFVRxJpHygx8g

### Expired JWT
GET http://localhost:5001/packages HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2NzIxMzM1OTcsImV4cCI6MTY3MjEzMzU5NywiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsIkdpdmVuTmFtZSI6IkpvaG5ueSIsIlN1cm5hbWUiOiJSb2NrZXQiLCJFbWFpbCI6Impyb2NrZXRAZXhhbXBsZS5jb20iLCJSb2xlIjpbIk1hbmFnZXIiLCJQcm9qZWN0IEFkbWluaXN0cmF0b3IiXX0.-DaJJYmAl814aoq0GsvdFiSYfvdRWbBCFeFDhZnq4vg

### Invalid Signature JWT
GET http://localhost:5001/packages HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ0ZXN0IjoidGVzdCwidXJuOmV4YW1wbGU6Y2xhaW0iOnRydWUsImlhdCI6MTY3MjIyNjE2NywiaXNzIjoidXJuOmV4YW1wbGU6aXNzdWVyIiwiYXVkIjoidXJuOmV4YW1wbGU6YXVkaWVuY2UiLCJleHAiOjE2NzIyMzMzNjd9.-dH-Nf0OYm0MFV3RSVGnozmPItTKhq7B7MAdNatBI4Q